[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "myproject"
authors = [{name = "Mohan Zhang", email = "mohanzhang@example.com"}]
dynamic = ["version", "description"]
